version: '3'
services:

  nginx:
    image: nginx:1.17.8
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    links: 
      - uwsgi
    ports:
      - "80:80"

  uwsgi:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - ./app:/var/www/app
    ports: 
      - "3031:3031"
